import React from 'react'

const RefundCancellationPolicy = () => {
    return (
        <div>
            <h1>
            Refund and Cancellation Policy
            </h1>
            <div class="elementor-widget-container">
				<p>&nbsp;</p>
                <p>Our focus is complete customer satisfaction. Please read the fine prints of each product before buying it, it provides all the details about the services or the product you purchase.<br/><br/><strong>Shipping</strong><br/>Please refer to the product page for estimated shipping and delivery timelines. Our delivery partners make every effort to ensure orders reach you in about 2- 9 days. The estimated delivery times are indicative and depend on your location as well as local administration controls, and, on some occasions, there might be some unavoidable delays beyond our control. We will keep you informed in case of any delays.<br/><br/><strong>Returns</strong><br/>Our policy lasts 7 days. If 7 days have gone by since you received your order, unfortunately, we can’t offer you a refund or exchange.<br/><br/>To be eligible for a return, your item must be unused and in the same condition that you received it. It must also be in the original packaging.<br/><br/>To complete your return, we require a receipt or proof of purchase. In order to initiate a return/refund, please write to&nbsp;<a href="mailto:Infoprolifictech@gmail.com">Infoprolifictech@gmail.com</a> with complete details of your order.<br/><br/><strong>Refunds (if applicable)</strong><br/>Once your return is received and inspected, we will send you an email to notify you that we have received your returned item. We will also notify you of the approval or rejection of your refund.<br/><br/>If the refund is approved, then your refund will be processed after deduction of shipping fee, convenience fee and, bank charges. It can take up to 10 days for the refund to be reflected in your account.<br/><br/><strong>Late or missing refunds (if applicable)</strong><br/>If you haven’t received a refund yet, first check with your bank / credit card company. There is often some processing time before a refund is posted. If you’ve done all of this and you still have not received your refund yet, please contact us at&nbsp;infoprolifictech@gmail.com<br/><br/></p>
                <h3>Cancellation</h3>
                <p><br/><br/></p>
                <ol><li><strong> Cancellation before Shipment –</strong> If you need to cancel your order before it has been shipped, please send an email to: &nbsp;<a href="mailto:infoprolifictech@gmail.com">infoprolifictech@gmail.com</a> with Subject: Order Cancellation-&lt;<em>Order Number</em>&gt;, where&nbsp;<em>Order Number</em>is the actual order number that you received after placing the order. The request will be processed in 3 business days.</li><li><strong> Cancellation Post Shipment (Before Delivery) –</strong> If you cancel the order after it has been shipped but has not been delivered yet, please send an email to: &nbsp;&nbsp;<a href="mailto:infoprolifictech@gmail.com">infoprolifictech@gmail.com</a> with Subject: Order Cancellation-&lt;<em>Order Number</em>&gt;, where&nbsp;<em>Order Number</em>is the actual order number that you received after placing the order.</li></ol><ul><li>As we work with a third party agency for Courier, there might be a case, where we have handed over the package to Courier person. Delivery will be attempted in such a case, please don’t accept the delivery.</li><li>We’ll check the returned package and based on our verification report of package/condition, will process the request in 3 business days.</li></ul><h3>‘No Questions Asked’ 100% Refund policy for courses</h3>
                <p><br/><br/></p><ol><li>Prolific Tech offers a ‘No questions asked’ refund policy for all its courses.</li><li>At any point during your course experience, if you are unsatisfied with the performance, you can choose to ask for a refund by mailing us at&nbsp;infoprolifictech@gmail.com</li><li>The refund will be transferred to you based on all the scheduled sessions (attended or not) in your original payment method.</li><li>The refund amount will be calculated based on the per session cost considering the final discounted price you paid for the complete course.</li><li>For all courses that come with a physical kit, there is a separate cost for the sessions and for the kits. So the refund amount will only be calculated and remitted for the remaining sessions. And for the kit the return policy mentioned above in section ‘Returns &amp; Cancellation Policy for Kits’ will apply.</li></ol><h5>&nbsp;</h5>
                <p>&nbsp;</p><p>&nbsp;</p>						
            </div>
        </div>
    )
}

export default RefundCancellationPolicy
