import React from 'react'

const TermsAndCondition = () => {
    return (
        <div>
            <h1>Terms & Conditions</h1>
            <br />
            <div class="elementor-widget-container">
				<p><strong>1.0 PURPOSE OF THIS SITE</strong></p>
                <p>Welcome to https://prolifictech.in (“Site” or “Prolific Tech“). This Site is owned and operated by Prolific Tech. You may be accessing our Site from a computer or mobile phone device (through an iOS or Android application, for example) and these Terms of Use govern your use of our Site and your conduct, regardless of the means of access. You may also be using our satellite sites / subdomains (“Sub-Sites“), such as prolifictech.in/contact-2/, prolifictech.in/all-courses-2/, <a href="prolifictech.in/about-us-2/">prolifictech.in/about-us-2/</a>,&nbsp; or other individual sub-sites we have set up to serve individual customers or deliver distinct consumer experiences. These Terms of Use govern all the products offered on the Site and Sub-Sites.</p>
                <p>The Site is only to be used for your personal non-commercial use and information. Your use of the services and features of the Site shall be governed by these Terms and Conditions (hereinafter“Terms of Use“) along with the Privacy Policy, and Cancellation &amp; Refund Policy (together&nbsp;“Policies“) as modified and amended from time to time.</p>
                <p>By mere accessing or using the Site, you are acknowledging, without limitation or qualification, to be bound by these Terms of Use and the Polices, whether you have read the same or not.&nbsp;ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING. If you do not agree to any of the terms enumerated in the Terms of Use or the Policies, please do not use the Site. You are responsible to ensure that your access to this Site and material available on or through it are legal in each jurisdiction, in or through which you access or view the site or such material.</p>
                <p>Prolific Tech reserves the right to change the particulars contained in the Terms of Use or the Policies from time to time and at any time, without notice to its users and in its sole discretion. If Prolific Tech decides to change the Terms of Use or Policies, Prolific Tech will post the new version of the Terms of Use or the Policies on the Site and update the date specified above. Any change or modification to the Terms of Use and the Policies will be effective immediately from the date of such upload of the Terms of Use and Policies on the Site. Your continued use of the Site following the modifications to the Terms of Use and Policies constitutes your acceptance of the modified Terms of Use and Policies whether or not you have read them. For this reason, you should frequently review these Terms of Use, our Guidelines and Rules and any other applicable policies, including their dates, to understand the terms and conditions that apply to your use of the Site.</p>
                <p><strong>1.1 PRIVACY PRACTICES</strong></p>
                <p>We understand the importance of safeguarding your personal information and we have formulated a Privacy Policy , to ensure that your personal information is sufficiently protected. Apart from these Terms of Use, the Privacy Policy shall also govern your visit and use of the Site. Your continued use of the Site implies that you have read and accepted the Privacy Policy and agree to be bound by its terms and conditions. You consent to the use of personal information by Prolific Tech in accordance with the terms of and purposes set forth in the Privacy Policy, the same may be subject to amendment from time to time at the sole discretion of Prolific Tech.</p>
                <p>Prolific Tech or its affiliates may record any or all sessions for record-keeping, quality assurance, and training purposes.</p>
                <p><strong>1.2 YOUR ACCOUNT</strong></p>
                <p>You will be responsible for maintaining confidentiality of your account, password, and restricting access to your computer, and you hereby accept responsibility for all activities that occur under your account and password. You acknowledge that the information you provide, in any manner whatsoever, are not confidential or proprietary and does not infringe any rights of a third party.</p>
                <p>If you are accessing, browsing and using the Site on someone else’s behalf; you represent that you have the authority to bind that person to all the terms and conditions herein. In the event that the person refuses to be bound as the principal to the Terms of Use, you agree to accept liability for any harm caused by any wrongful use of the Site resulting from such access or use of the Site.</p>
                <p>If you know or have reasons to believe that the security of your account has been breached, you should contact us immediately at the Contact Information provided below. If we have found a breach or suspected breach of the security of your account, we may require you to change your password, or suspend your account without any liability to Prolific Tech.</p>
                <p>We reserve the right to refuse service and/or terminate accounts without prior notice if these Terms of Use are violated or if we decide, in our sole discretion, that it would be in Prolific Tech’s best interests to do so. You are solely responsible for all content that you upload, post, email or otherwise transmit via the Site. The information provided to us shall be maintained by us in accordance with our Privacy Policy.</p>
                <p><strong>1.3 PRODUCT &amp; SERVICES INFORMATION</strong></p>
                <p>Prolific Tech attempts to be as accurate as possible in the description of the product on the Site. The Site may contain typographical errors or inaccuracies and may not be complete or current, and Prolific Tech reserves the right to correct, change or update information, errors, inaccuracies or omissions at any time without prior notice. Please note that such errors, inaccuracies or omissions may also relate to pricing and availability.</p>
                <p><strong>1.4 PRICING INFORMATION</strong></p>
                <p>Prices and availability of products and services provided on the site are subject to change without prior notice and at the sole discretion of Prolific Tech. Prolific Tech may revise and cease to make available any product/ services at any time.</p>
                <p><strong>1.5 MODE OF PAYMENT</strong></p>
                <p>Payments for the products available on the Site or on our Sub-Sites may be made in the following ways:</p>
                <p>Visa/MasterCard/Maestro Cards, Net Banking, Wallet, UPI.</p>
                <p><strong>1.6 CHAT FUNCTIONALITY</strong></p>
                <p>The Chat Functionality has been provided to help you with any and all Site related queries. Any use of this service shall be subject to the following conditions:</p><ul><li>Prolific Tech may suspend the chat service at any time without notice.</li><li>Prolific Tech or its executives are not responsible for any delay caused in attending to or replying to the queries via chat.</li><li>While ‘chatting’ you may not communicate any objectionable information i.e. unlawful, threatening, abusive, defamatory, obscene information.</li><li>The chat room shall not be used by the end-user to sell any products, to give suggestion on business opportunity or any other form of solicitation.</li><li>You may proceed further and chat with our online customer care executive only if you agree to the above terms and conditions.</li></ul>
                <p><strong>1.7 USER CONTENT</strong></p>
                <p>The information, photo, image, chat communication, text, software, data, music, sound, graphics, messages, videos or other materials transmitted, uploaded, posted, emailed or otherwise made available to us (“User Content“), are entirely your responsibility and we will not be held responsible, in any manner whatsoever, in connection to the User Content. You agree to not encourage or assist or engage others as well as yourself in transmitting, hosting, displaying, uploading, modifying, publishing transmitting, updating or sharing any information that</p><ol><li>belongs to another person and to which the user does not have any right to;</li><li>is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, pedophilic, libelous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;</li><li>harms minors in any way;</li><li>infringes any patent, trademark, copyright or other proprietary rights;</li><li>violates any law for the time being in force;</li><li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li><li>impersonate another person;</li><li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li><li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</li></ol>
                <p>Prolific Tech shall in no way be held responsible for examining or evaluating User Content, nor does it assume any responsibility or liability for the User Content. Prolific Tech does not endorse or control the User Content transmitted or posted on the Site by you and therefore, accuracy, integrity or quality of User Content is not guaranteed by Prolific Tech. You understand that by using the Site, you may be exposed to User Content that is offensive, indecent or objectionable to you. Under no circumstances will Prolific Tech be liable in any way for any User Content, including without limitation, for any errors or omissions in any User Content, or for any loss or damage of any kind incurred by you as a result of the use of any User Content transmitted, uploaded, posted, e-mailed or otherwise made available via the Site. You hereby waive all rights to any claims against Prolific Tech for any alleged or actual infringements of any proprietary rights, rights of privacy and publicity, moral rights, and rights of attribution in connection with User Content.</p>
                <p>You hereby acknowledge that Prolific Tech has the right (but not the obligation) in its sole discretion to refuse to post or remove any User Content and further reserves the right to change, condense, or delete any User Content. Without limiting the generality of the foregoing or any other provision of these Terms and Conditions, Prolific Tech has the right to remove any User Content that violates these Terms and Conditions or is otherwise objectionable and further reserves the right to refuse service and/or terminate accounts without prior notice for any users who violate these Terms and Conditions or infringe the rights of others.</p>
                <p>If you wish to delete your User Content on our Site or in connection with our mobile applications, please contact us by email at <a href="mailto:Infoprolifictech@gmail.com">Infoprolifictech@gmail.com</a> and request you to include the following personal information in your deletion request: first name, last name, user name/screen name (if applicable), email address associated with our Site and/or mobile applications, and your reason for deleting. We may not be able to process your deletion request if you are unable to provide such information to us. Please allow up to 10 business days to process your deletion request.</p>
                <p><strong>1.8 INTELLECTUAL PROPERTY RIGHTS</strong></p>
                <p>The&nbsp;“Prolific Tech”&nbsp;name and logo and all related product and service names, design marks and slogans are the trademarks, logos or service marks (hereinafter referred to as&nbsp;“Marks“) of Prolific Tech. No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any Marks in any manner. Marks displayed on this Site, whether registered or unregistered, of Prolific Tech or others, are the intellectual property of their respective owners, and Prolific Tech shall not be held liable in any manner whatsoever for any unlawful, unauthorized use of the Marks.</p>
                <p>The compilation (meaning the collection, arrangement and assembly) of the content on the Site is the exclusive property of Prolific Tech and are protected by the Indian copyright laws and International treaties. Consequently, the materials on this Site shall not be copied, reproduced, duplicated, republished, downloaded, posted, transmitted, distributed or modified in whole or in part or in any other form whatsoever, except for your personal, non-commercial use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying, reproducing, duplicating, republishing, posting, transmitting, distributing or modifying.<br/>All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips, downloads, video clips and written and other materials that are part of this Site (collectively, the&nbsp;“Contents“) are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Site for your personal use only. We also grant you a limited, revocable, non-transferable, and non-exclusive license to create a hyperlink to the home page of the Site for personal, non-commercial use only. The Contents and software on this Site are to be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, re-publication, display, or performance, of the Contents on this Site is strictly prohibited. Unless Prolific Tech explicitly provides to the contrary, all Contents are copyrighted, trademarked, trade dressed and/or other intellectual property owned, controlled or licensed by Prolific Tech, any of its affiliates or by third parties who have licensed their materials to Prolific Tech and are protected by Indian copyright laws and international treaties.</p>
                <p><strong>1.9 LIMITED LICENSE</strong></p>
                <p>Prolific Tech grants you limited, non-exclusive, non-transferable, non-sublicensable license to access, and make personal and non-commercial use of the Site. All rights not expressly granted to you in these Terms of Use, are reserved and retained by the Site and its affiliates.<br/>Prolific Tech reserves the right, at any time, without notice, and at its sole discretion, to terminate your license to use the Site and to block and prevent your future access the Site.</p>
                <p><strong>2.0 REPRESENTATIONS AND WARRANTIES</strong></p>
                <p>This Site is provided to you “AS IS”. We make no representations regarding the use of or the result of the use/depiction of the Contents on the Site in terms of their correctness, accuracy, reliability, or otherwise. Prolific Tech shall not be liable for any loss suffered in any manner by the user as a result of depending directly or indirectly on the depiction of the Content on this Site.</p>
                <p>You acknowledge that this Site is provided only on the basis set out in the Terms of Use. Your uninterrupted access or use of this Site on this basis may be prevented by certain factors outside our reasonable control including, without limitation, the unavailability, inoperability or interruption of the internet or other telecommunications services or as a result of any maintenance or other service work carried out on this Site.</p>
                <p>Prolific Tech shall have the right, at any time, to change or discontinue any aspect or feature of the Site, including, but not limited to, content, hours of availability, and equipment needed for access or use. Further, the Site may discontinue disseminating any portion of information or category of information. Prolific Tech does not accept any responsibility and will not be liable for any loss or damage whatsoever arising out of or in connection with any ability/inability to access or to use the Site.</p><p>For any general information posted on the Site, users must not infer or assume that such information necessarily applies to them.</p>
                <p><strong>2.1 DISCLAIMER OF WARRANTY AND LIMITATION OF LIABILITY</strong></p>
                <p>THE SITE IS PRESENTED “AS IS.” NEITHER WE NOR OUR HOLDING, SUBSIDIARIES, AFFILIATES, PARTNERS, OR LICENSORS MAKE ANY REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, IN CONNECTION WITH THESE TERMS AND CONDITIONS OR THE SITE OR ANY OF THE CONTENT, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE, EXCEPT TO THE EXTENT SUCH REPRESENTATIONS AND WARRANTIES ARE NOT LEGALLY EXCLUDABLE.</p>
                <p>YOU AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER WE NOR OUR HOLDING, SUBSIDIARIES, AFFILIATES, PARTNERS, OR LICENSORS WILL BE RESPONSIBLE OR LIABLE (WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE) UNDER ANY CIRCUMSTANCES FOR ANY (a) INTERRUPTION OF BUSINESS; (b) ACCESS DELAYS OR ACCESS INTERRUPTIONS TO THE SITE; (c) DATA NON-DELIVERY, LOSS, THEFT, MISDELIVERY, CORRUPTION, DESTRUCTION OR OTHER MODIFICATION; (d) LOSS OR DAMAGES OF ANY SORT INCURRED AS A RESULT OF DEALINGS WITH OR THE PRESENCE OF OFF-WEBSITE LINKS ON THE SITE; (e) VIRUSES, SYSTEM FAILURES OR MALFUNCTIONS WHICH MAY OCCUR IN CONNECTION WITH YOUR USE OF THE SITE, INCLUDING DURING HYPERLINK TO OR FROM THIRD PARTY WEBSITES; (f) ANY INACCURACIES OR OMISSIONS IN CONTENT; OR (g) EVENTS BEYOND THE REASONABLE CONTROL OF PROLIFIC TECH. WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT DEFECTS OR ERRORS WILL BE CORRECTED.</p>
                <p>FURTHER, TO THE FULLEST EXTENT PERMITTED BY LAW, NEITHER WE NOR OUR SUBSIDIARIES, AFFILIATES, PARTNERS, OR LICENSORS WILL BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING LOST PROFITS) RELATED TO THE SITE OR YOUR USE THEREOF REGARDLESS OF THE FORM OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND IN NO EVENT SHALL OUR MAXIMUM AGGREGATE LIABILITY EXCEED.</p>
                <p>YOU AGREE THAT NO CLAIMS OR ACTION ARISING OUT OF, OR RELATED TO, THE USE OF THE SITE OR THESE TERMS AND CONDITIONS MAY BE BROUGHT BY YOU MORE THAN ONE (1) YEAR AFTER THE CAUSE OF ACTION RELATING TO SUCH CLAIM OR ACTION AROSE. IF YOU HAVE A DISPUTE WITH US OR ARE DISSATISFIED WITH THE SITE, TERMINATION OF YOUR USE OF THE SITE IS YOUR SOLE REMEDY. WE HAVE NO OTHER OBLIGATION, LIABILITY, OR RESPONSIBILITY TO YOU.</p>
                <p>This disclaimer constitutes an essential part of this Terms of Use.</p>
                <p><strong>2.2 LINKS AND THIRD PARTY SITES</strong></p>
                <p>References on the Site to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you. This does not in any way constitute or imply Prolific Tech endorsement, sponsorship or recommendation of the third party, information, product or service or any association and relationship between Prolific Tech and those third parties.</p>
                <p>Prolific Tech is not responsible for the content of any third party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to link to any such third party websites, you do so entirely at your own risk. Prolific Tech do not assume any responsibility for examining or evaluating the offerings of the off-websites pages or any other websites linked from the Site. We shall not be responsible for the actions, content, products, or services of such pages and websites, including, without limitation, their privacy policies and terms and conditions. You should carefully review the terms and conditions and privacy policies of all off-website pages and other websites that you visit via the Site.</p>
                <p><strong>2.3 TERMINATION</strong></p>
                <p>These Terms of Use are effective unless and until terminated by either you or Prolific Tech.</p>
                <p>You may terminate the Terms of Use at any time, provided that you discontinue any further use of this Site. Prolific Tech may terminate the Terms of Use at any time and may do so without notice, and accordingly deny you access to the Site, such termination will be without any liability to the Site.</p>
                <p>Upon any termination of the Terms of Use by either you or Prolific Tech, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the Terms of Use or otherwise. Any such termination of the Terms of Use shall not cancel your obligation to pay for the product already ordered from the Site or affect any liability that may have arisen under the Terms of Use.</p>
                <p><strong>2.4 INDEMNITY</strong></p>
                <p>You agree to defend, indemnify and hold harmless Prolific Tech, its employees, directors, officers, agents and their successors and assigns, its holding, subsidiaries, affiliates, partners, or licensors from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney’s fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to Prolific Tech or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under the Terms of Use, or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of the Terms of Use.</p>
                <p><strong>2.5 GOVERNING LAW AND JURISDICTION</strong></p>
                <p>The Terms of Use and the Policies shall be construed in accordance with the applicable laws of India. For proceedings arising therein the Courts in Delhi shall have exclusive jurisdiction.</p>
                <p>Any dispute or difference either in interpretation or otherwise, of the Terms of Use and other Policies on the Site, between the parties hereto, shall be referred to an independent arbitrator who will be appointed by mutually and his decision shall be final and binding on the parties hereto. The above arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 as amended from time to time. The seat of arbitration shall be held in Delhi.</p>
                <p>Without any prejudice to particulars listed in Clause 10 above, Prolific Tech shall have the right to seek and obtain any injunctive, provisional or interim relief from any court of competent jurisdiction to protect its trade-mark or other intellectual property rights or confidential information or to preserve the status quo pending arbitration.</p>
                <p><strong>2.6 SITE SECURITY</strong></p>
                <p>You are prohibited from violating or attempting to violate the security of the Site, including, without limitation,</p><ol><li>accessing data not intended for you or logging onto a server or an account which you are not authorized to access;</li><li>attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization;</li><li>attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, “flooding,” “spamming,” “mail bombing” or “crashing;”</li><li>sending unsolicited email, including promotions and/or advertising of products or services; or</li><li>forging any header or any part of the header information in any email or newsgroup posting.</li></ol>
                <p>Violations of system or network security may result in civil or criminal liability. Prolific Tech is entitled to investigate occurrences that may involve such violations and may involve, and co-operate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search this Site other than the search engine and search agents available from Prolific Tech on this Site and other than generally available third party web browsers (e.g., Google Chrome, Microsoft Explorer).</p>
                <p><strong>2.7 ENTIRE AGREEMENT</strong></p>
                <p>If any part of these Terms of Use is determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use shall continue to be in effect. Unless otherwise specified herein, these Terms of Use constitutes the entire agreement between you and Prolific Tech with respect to the Site/services and it supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written.</p>
                <p>Prolific Tech’s failure to act with respect to a breach by you or others does not waive its right to act with respect to the breach or subsequent and similar breaches.</p>						</div>
        </div>
    )
}

export default TermsAndCondition
